version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 836047599732.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=836047599732.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/coworking-service
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t coworking-service .
      - docker tag coworking-service:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
