apiVersion: apps/v1
kind: Deployment
metadata:
  name: coworking-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coworking-service
  template:
    metadata:
      labels:
        app: coworking-service
    spec:
      containers:
      - name: coworking-service
        image: 836047599732.dkr.ecr.us-east-1.amazonaws.com/demok8s:latest
        ports:
        - containerPort: 80
        env:
        - name: EXAMPLE_ENV_VAR
          valueFrom:
            configMapKeyRef:
              name: coworking-config
              key: example.env
        - name: SECRET_ENV_VAR
          valueFrom:
            secretKeyRef:
              name: coworking-secrets
              key: secret.env
