apiVersion: v1
kind: Service
metadata:
  name: coworking-service
  namespace: default
spec:
  selector:
    app: coworking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
